services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: ansan-jarvis.duckdns.org
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://ansan-jarvis.duckdns.org/
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
